#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint AirBnb Standards
npm run lint ||
(
    echo '🙈👷🔨❌ Yoo, your code looks disgusting. Check linter 🙈👷🔨❌
          Run npm run lint, add changes and try commit again.';
    false;
)

npm run lint:staged

# If everything passes... Now we can commit
echo '🎉🎉🎉🎉 You win this time... I am committing this now. ✨🚀🏄‍♂️🍻'
